### ISSUE TITLE
game seems stuck

### ISSUE THREAD

**Issue by houhoulis** [timburgan/timburgan#18300]
Hi cc @timburgan

**Comment by DalpatRathore** [comment]
The game stuck for the last two days.

**Comment by michaelprimo** [comment]
Agree. No one is playing for some reason. cc @timburgan

**Comment by odil-io** [comment]
I'm getting notifications of comments i can't recall placing. Might be just me, but i got a few notifications the last days that probably has to to with what has been said above.

**Comment by timburgan** [comment]
:wave: @houhoulis @DalpatRathore @michaelprimo @odil-io Thanks for letting me know. I will try to find time to look this week, resolve this and a bunch of the other issues that folks have pointed out

**Comment by DalpatRathore** [comment]
hey! @timburgan 
  &nbsp;&nbsp; if you have time this week or any, please also consider reviewing my contributions in the pull request - #18182 `.

Thanks

**Comment by donno2048** [comment]
++

**Comment by donno2048** [comment]
I figured out what went wrong and managed to fix it (#18429) using an invalid move. I hope it's fine I "cheated"
cc @timburgan

**Comment by timburgan** [comment]
Can you help explain it to me @donno2048 ? I'm curious if the where the underlying problem was so I can fix it

**Comment by donno2048** [comment]
> Can you help explain it to me @donno2048 ? I'm curious if the where the underlying problem was so I can fix it


Of course, first of all, I noticed the last issue that made a move is #18278, but if you look closely the move is only being made in the _chess.pgn_ file but not in the _README.md_ (d94ca3d638b942a5a13565f034ab8e560e0b2814 exists but there is no corresponding commit afterward) that's because the action (https://github.com/timburgan/timburgan/actions/runs/1580202982) failed before altering the _README_ file without a fallback mechanism since the _chess.pgn_ has changed I assumed if I make another legal move (while assuming b1c3 is the last move) the code will add it to _chess.pgn_ and apply to _README.md_ (and it happened in fc2f54cf569adb093cd617ad0936b30179fe17c9, 315c16d1b0e27d5bd5eea5ccf1ee88502355d4d8) the solution for the next time is to make sure both changes are being applied in the same commit, thus, if they're failing they will both fail.

**Comment by donno2048** [comment]
cc @timburgan
